### ISSUE TITLE
config.yml: documentation of `images:` vs `image:` field in `queues` 

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1319]
These are just some comments on the `images:` list in the configuration template 

https://github.com/Azure/az-hop/blob/3b943a965e72d8757d1b1ec36bdc1e15e4074ebb/config.tpl.yml#L258-L339

 1. It would be great to document what the metadata in this list is actually used for.
   E.g. if an admin just builds the images via packer, are the `publisher`, `offer`, ... metadata fields actually used in any way (?)
 2. While there _are_ prebuilt offers for some of the listed images on the marketplace, the `publisher` and `offer` names do not necessarily match the ones listed here. This can be confusing to a new user
  
Example 1:
```yaml
  - name: base-centos79-v2-rdma
    publisher: azhop
    offer: CentOS
    sku: 7.9-gen2-rdma-nogpu
    hyper_v: V2
    os_type: Linux
    version: 7.9
```
on the marketplace
```yaml
  - publisher: azhpc
    offer: azhop
    sku: centos-7_9
    version: latest
```
Example 2:
```yaml
  - name: azhop-almalinux85-v2-rdma-gpgpu
    publisher: azhop
    offer: almalinux
    sku: 8_5-hpc-gen2
    hyper_v: V2
    os_type: Linux
    version: 8.5
```
on the marketplace:
```yaml
  - publisher: almalinux
    offer: almalinux-hpc
    sku: 8_5-hpc-gen2
    version: 8.5.20211210
```

cc @matt-chan
