### ISSUE TITLE
mounts defined in config file are not accessible for domain users

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1324]
Add domain users access when creating the mount directory
```
  - name: Create "{{mounts[item].mountpoint}}" directory mountpoint
    file:
      path: '{{mounts[item].mountpoint}}'
      state: directory
      mode: '0755'
    loop: "{{mounts | list}}"
    when: item != 'home'
```
