### ISSUE TITLE
toolchain installation failure

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1429]
## Version
1.0.33+

When running the ./toolset/scripts/install.sh not being root, if the /tmp folder contains unaccessible files or folders, the following ansible task will failed to return the location of the azcopy extraction

```yml
    - name: "AzCopy: Find azcopy (CentOS)"
      find:
        paths: /tmp
        patterns: "azcopy"
        file_type: file
        recurse: true
      register: azcopy_file_path
```
