### ISSUE TITLE
 The default configuration file is wrong if not joining an existing Domain

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1511]
## Version
1.0.35

## Expected Behavior

Using the config.tpl.yml file as a config file template when not joining an existing domain should allow a proper deployment

## Actual Behavior
Failure when building with Terraform
![image](https://user-images.githubusercontent.com/7349410/236668001-e10d645b-15d0-4097-8cac-d0d903506ab2.png)

## Steps to Reproduce the Problem

have a configuration file with the below content

```yml
domain:
  name: "hpc.azure"
  #domain_join_ou: "OU=azhop" # OU to set the machine in. Make sure the OU exists in the domain as it won't be created for you
  use_existing_dc: false # Set to true if you want to join a domain with existing DC
  domain_join_user:
    username: hpcadmin
    password_key_vault_name: '{{key_vault}}' # name_for_the_key_vault_with_the_domain_join_password
    password_key_vault_resource_group_name: '{{resource_group}}' # resource_group_name_for_the_key_vault_with_the_domain_join_password
    password_key_vault_secret_name: 'hpcadmin-password' # key_vault_secret_name_for_the_domain_join_password
  # additional settings when using an existinf DC
  existing_dc_details: 
    domain_controller_names: ["dc1", "dc2"]
    domain_controller_ip_addresses: ["192.168.1.100", "192.168.1.101"]
    private_dns_servers: ["192.168.1.53", "192.168.2.53"]

```
