### ISSUE TITLE
Terraform : Lustre cluster is created even if lustre.create is false

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1515]
## Version
1.0.35

## Expected Behavior

No lustre cluster is created if lustre.create is false in the configuration file.

## Actual Behavior

a lustre cluster is created

## Steps to Reproduce the Problem

add this in your config file and then run `./build.sh -a apply` 
```yml
# Lustre cluster is optional and can be used to create a Lustre cluster in the environment.
lustre:
  create: false # true or false to create a lustre cluster
  rbh_sku: "Standard_D8d_v4"
  mds_sku: "Standard_D8d_v4"
  oss_sku: "Standard_D32d_v4"
  oss_count: 2
  hsm_max_requests: 8
  mdt_device: "/dev/sdb"
  ost_device: "/dev/sdb"

```
