### ISSUE TITLE
Terraform : ANF is created even when anf.create is false

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1517]
## Version
1.0.35

## Expected Behavior

If anf.create is set to false, then don't build ANF

## Actual Behavior

ANF is built even if anf.create is false

## Steps to Reproduce the Problem
define ANF as below and build the environment 
```yml
anf:
  create: false
  # Size of the ANF pool and unique volume
  homefs_size_tb: 4
  # Service level of the ANF volume, can be: Standard, Premium, Ultra
  homefs_service_level: Standard

```
