### ISSUE TITLE
Make grafana optional

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1591]
## Describe the feature
Allow grafana/telegraf monitoring be enabled/disabled

```
# Options for the monitoring and alerting stack 
monitoring:
  azure_monitor_agent: false # Install Azure Monitor Agent on static infra VMs
  telegraf: false # Install telegraf on static infra VMs and dynamic compute nodes
  grafana: false # Deploy a Grafana instance with pre-defined dashboards

```
