### ISSUE TITLE
automatic security updates

### ISSUE THREAD

**Issue by ltalirz** [Azure/az-hop#1594]
## In what area(s)?

> /area administration
> /area ansible
> /area autoscaling
> /area configuration
> /area cyclecloud
> /area documentation
> /area image
> /area job-scheduling
> /area monitoring
> /area ood
> /area remote-visualization
> /area user-management

## Describe the feature
Many playbooks currently contain a task
```yaml
  - name: update packages for security
    become: true
    yum:
      name: '*'
      state: latest
      exclude: cyclecloud*
```

Not only does this task slow down the playbooks, it also does not keep the systems up to date when you are not running playbooks.

There are ansible roles for this, such as https://github.com/geerlingguy/ansible-role-security that will install cronjobs (yum-cron for rhel-based, unattended-upgrades for debian-based systems) to keep the VMs up to date at all times.
I believe we should use them
