### ISSUE TITLE
Don't override OOD_CORE if not using remote_winviz

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1598]
## Describe the feature
Add a test around this block in ood.yml

```
  - name: cleanup ood_core gem directory
    file:
      state: absent
      path: "/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/{{ ondemand_version }}/gems/ood_core-{{ood_core_version}}"

  - name: get the ood_core specific gem
    git:
      repo: "https://github.com/xpillons/ood_core.git"
      dest: "/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/{{ ondemand_version }}/gems/ood_core-{{ood_core_version}}"
      version: "azhop/{{ood_core_version}}"
      force: yes

```
