### ISSUE TITLE
Existing AD Bug - domain_join_ou not propagated to Ansible

### ISSUE THREAD

**Issue by thielen24** [Azure/az-hop#1627]
## Version
1.0.36

## In what area(s)?
/area ansible

## Expected Behavior
domain/domain_join_ou entry from the config.yml would be propagated appropriately to the global_variables used by ansible when attempting a deployment with an existing AD domain.

## Actual Behavior
tf/outputs.tf and tf/templates/global_variables.tmpl don't contain the above variable, despite it being needed in playbooks/roles/domain_join/tasks/main.yml. No variable is passed to ansible to use.

## Steps to Reproduce the Problem
Attempt a deployment using an existing AD and specify a domain_join_ou.

**Comment by xpillons** [comment]
the domain_join_ou value is provided when calling the role. For example in the `playbooks/linux.yml` file

```
    - name: Join domain
      include_role:
        name: domain_join
      vars:
        domain_admin: "{{ad_join_user}}"
        domain_password: "{{password.stdout}}"
        domain: "{{domain_name}}"
        domain_homedir: "{{homedir_mountpoint}}"
        domain_mount_ip: "{{anf_home_ip}}"
        domain_mount_path: "{{anf_home_path}}"
        domain_mount_opts: "{{anf_home_opts}}"
        domain_join_ou: "{{domain.domain_join_ou | default('')}}"

```

do you see any specific error when running install.sh ?
