### ISSUE TITLE
Users are not added in AD when domain is defined and domain.use_existing_dc is false

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1629]
## Version
1.0.36

## Expected Behavior
Users added in AD

## Actual Behavior
Users not added in AD

## Steps to Reproduce the Problem
Define a config containing a domain section like this 
```
domain:
  name: "hpc.azure"
  #domain_join_ou: "OU=azhop" # OU to set the machine in. Make sure the OU exists in the domain as it won't be created for you
  use_existing_dc: false # Set to true if you want to join a domain with existing DC
  domain_join_user:
    username: hpcadmin
    password_key_vault_name: name_for_the_key_vault_with_the_domain_join_password
    password_key_vault_resource_group_name: resource_group_name_for_the_key_vault_with_the_domain_join_password
    password_key_vault_secret_name: key_vault_secret_name_for_the_domain_join_password
  # additional settings when using an existinf DC
  existing_dc_details: 
    domain_controller_names: ["dc1", "dc2"]
    domain_controller_ip_addresses: ["192.168.1.100", "192.168.1.101"]
    private_dns_servers: ["192.168.1.53", "192.168.2.53"]

```
