### ISSUE TITLE
slurm UID/GID are not well assigned in the slurm client ansible role

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1655]
## Version
1.0.37

## Description

in playbooks/roles/slurmclient/tasks/main.yml 
- slurm_uid is assigned to slurm group
- slurm_gid is assigned to slurm user
This should be set in the other way

```
- name: add slurm group 
  group:
    name: slurm
    gid: '{{ slurm_uid }}'
    state: present

- name: add slurm user
  user:
    name: slurm 
    group: slurm
    uid: '{{ slurm_gid }}'
    state: present

```
