### ISSUE TITLE
remote desktop jobs have a 6 cores hardcoded value

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#537]
The option for submitting a job for the remote desktop session have a 6 cores hardcoded value which prevent using different type of machine with less cores.
```
    submit: |
      ---
      script:
        native:
          - "-l"
          - "select=1:ncpus=6:slot_type=viz3d"
          - "-l"
          - "walltime=<%= '%02d:00:00' % hours %>"

```
