### ISSUE TITLE
use jetpack 8.2 for slurm

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#619]
we are currently on release 8.2 of Cycle, so use the same version for jetpack

```
- name: install jetpack 
  yum:
    name:
      -  https://packages.microsoft.com/yumrepos/cyclecloud/jetpack8-8.1.1-1451.x86_64.rpm 
    state: present
```
