### ISSUE TITLE
cyclecloud-slurm download version is not consistent

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#620]
releases 2.4.8 and 2.4.7 are used, add a variable to store the version and use the same version to avoid issues in the futur and allow an easier management of updates.

```
- name: download cc autoscale api 
  get_url:
    url: https://github.com/Azure/cyclecloud-slurm/releases/download/2.4.8/cyclecloud_api-8.1.0-py2.py3-none-any.whl 
    dest: /opt/cycle/slurm

- name: download cc jobsubmit plugin
  get_url:
    url: https://github.com/Azure/cyclecloud-slurm/releases/download/2.4.7/job_submit_cyclecloud_centos_20.11.7-1.so 
    dest: /usr/lib64/slurm/job_submit_cyclecloud.so

```
