### ISSUE TITLE
Error deploying when using existing vnet/subnets

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#778]
```
Error: Invalid index
│ 
│   on network_security_group.tf line 67, in resource "azurerm_subnet_network_security_group_association" "frontend":
│   67:   subnet_id                 = azurerm_subnet.frontend[count.index].id
│     ├────────────────
│     │ azurerm_subnet.frontend is empty tuple
│     │ count.index is 0
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.

```
```yml
network:
  create_nsg: true
  vnet:
    id: /subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/virtualNetworks/hpcvnet
    # When using an existing VNET, only the subnet names will be used and not the adress_prefixes
    subnets: 
      frontend: 
        name: frontend
      admin:
        name: admin
      netapp:
        name: netapp
      ad:
        name: ad
      compute:
        name: compute
```
version : 1.0.16
