### ISSUE TITLE
optimize the reboot time when installing AD

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#896]
Instead of having a fix 10mn wait time use somehing like this 

https://docs.ansible.com/ansible/2.9/modules/win_reboot_module.html

```
# Or you can make win_reboot validate exactly what you need to work before running the next task
- name: Validate that the netlogon service has started, before running the next task
  win_reboot:
    test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'

```
