### ISSUE TITLE
OOD installation failed when checking the chain certificate file existence

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#930]
ood installation is failing when checking if the chain certificate exists on the deployer VM if a password is required to run sudo commands.
Workaround => become: false

```
      - name: Check if a certificate chain file exists
        stat:
          path: '{{ ondemand_fqdn }}_chain.crt'
        register: sslcert_chain
        delegate_to: localhost
        connection: local
        become: false
```
